### ISSUE TITLE
Crash on Android 7.0

### ISSUE THREAD

**Issue by SudaNix** [alhazmy13/MediaPicker#10]
Duo to behavior change on Android 7.0, library start to produce following crash when trying to capture image from Camera:

"Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/mediapicker/images/afb88089-b317-4f37-99e7-9dcc131dd994.png exposed beyond app through ClipData.Item.getUri()"

In Android 7.0, "file://" is not allowed anymore to pass with Intent and should be replaced with "content://" while declaring a file provider in the manifest file.

**Comment by alhazmy13** [comment]
#12
