### ISSUE TITLE
Library will become inaccessible May 1st 2021 - Bintray is shutting down

### ISSUE THREAD

**Issue by prfarlow1** [alhazmy13/MediaPicker#113]
This library is in the Bintray repository, which is shutting down on May 1st, 2021. The library author has totally abandoned this project, so I doubt @alhazmy13 will update this library to live elsewhere like Jitpack or Maven Central. If he doesn't then this library will be totally unusable.

**Comment by alhazmy13** [comment]
Hi @prfarlow1 
I can confirm that MediaPicker is live in Jitpack
https://jitpack.io/#alhazmy13/MediaPicker

Thanks
