### ISSUE TITLE
Add support for selecting one image while enabling allowMulitpleImages flag

### ISSUE THREAD

**Issue by SudaNix** [alhazmy13/MediaPicker#15]
I suggest to support selecting one image by normal click while using Multiple Images Mode, as it's not clear to end users to use long click gestures in order to select images.

Current implementation, just close Image Gallery when click on the image without retrieving the path.

**Comment by alhazmy13** [comment]
#16

**Comment by alhazmy13** [comment]
cecef2010f8390b1ac9a73ff0b99fa991185612a

**Comment by alhazmy13** [comment]
Fixed with version 2.2.5 
cecef2010f8390b1ac9a73ff0b99fa991185612a
