### ISSUE TITLE
Can't receive the onActivityResult in fragment

### ISSUE THREAD

**Issue by mtx62** [alhazmy13/MediaPicker#20]
Greetings,
Dear Abdullah,

This is an information maybe more than a bug, but the onActivityResult will fire inside fragment.
Instead the main activity will receive the onActivityResult.

Best regards.
Abdulaziz Noor.

**Comment by alhazmy13** [comment]
Hi @mtx62 
Check this issue please: [startActivityForResult Never called in fragment](https://github.com/alhazmy13/MediaPicker/issues/11)
Thanks,,

**Comment by mtx62** [comment]
Hi Abdullah,
Thank you for your quick respond.
Best regards.

**Comment by TechRova** [comment]
in fragments use rxjava adapter

```
        new VideoPickerHelper(new VideoPicker.Builder(getActivity())
                .mode(VideoPicker.Mode.CAMERA_AND_GALLERY)
                .directory(VideoPicker.Directory.DEFAULT)
                .extension(VideoPicker.Extension.MP4)
                .enableDebuggingMode(true)

        ).getObservable().subscribe(new Observer<List<String>>() {
            @Override
            public void onSubscribe(Disposable d) {
                Log.d("Upload", "selected : "+d.isDisposed());

            }

            @Override
            public void onNext(List<String> mPaths) {
                Log.d("Upload", "selected : "+mPaths.get(0));
            }

            @Override
            public void onError(Throwable e) {
                Log.d("Upload", "selected : "+e.getMessage());

            }

            @Override
            public void onComplete() {
                Log.d("Upload", "selected :fin ");

            }
        }); 
```

You have to add @aar at the end of dependencies for this to build successfully.

implementation 'net.alhazmy13.MediaPicker:libary:2.4.4@aar'
implementation 'net.alhazmy13.MediaPicker:rxjava:2.4.4@aar'

-- latest rxjava and rxandroid dependencies
