### ISSUE TITLE
OnActivityResult VideoPicker

### ISSUE THREAD

**Issue by chrisferdian** [alhazmy13/MediaPicker#21]
please help me,
i got some error onActivityResult videopicker.

 java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference

for imagepicker, is going so good for me.
but, for videopicker, i got some error like this.
please help me, or fix this bug.

**Comment by alhazmy13** [comment]
I'll look to it.

**Comment by alhazmy13** [comment]
it should be fixed with version 2.3.0 #22
