### ISSUE TITLE
VideoPicker.VIDEO_PICKER_REQUEST_CODE is not public

### ISSUE THREAD

**Issue by 2hamed** [alhazmy13/MediaPicker#23]
Hello,

I just noticed that VideoPicker.VIDEO_PICKER_REQUEST_CODE and EXTRA_VIDEO_PATH are not public.

**Comment by karanatwal** [comment]
Yes i am facing same issue

**Comment by alhazmy13** [comment]
Hi @2hamed @karanatwal 
Thanks for your report, it should be fixed with version `2.3.1` #24
