### ISSUE TITLE
Selecting Images From Google Photos

### ISSUE THREAD

**Issue by mtx62** [alhazmy13/MediaPicker#25]
Greetings,
Dear Engr. Abdullah,

When I select an image from Google Photos I'm getting null,
the installed version is 2.3.1

Best regards.

**Comment by alhazmy13** [comment]
Hi @mtx62 
Can you please post the full stacktrace ?
and is the `allowMultipleImages` enabled?

**Comment by mtx62** [comment]
> 05-17 18:54:30.071 6007-6007/market.shopnow.app D/ImagePicker: onActivityResult() called with: requestCode = [5341], resultCode = [-1], data = [Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/19637/ORIGINAL/NONE/948348394 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F19637/ORIGINAL/NONE/948348394} }]
> 05-17 18:54:30.074 6007-7390/market.shopnow.app V/FA: Using measurement service
> 05-17 18:54:30.074 6007-7390/market.shopnow.app V/FA: Connecting to remote service
> 05-17 18:54:30.078 6007-7390/market.shopnow.app V/FA: Activity resumed, time: 322629369
> 05-17 18:54:30.255 6007-7390/market.shopnow.app V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 181
> 05-17 18:54:30.256 6007-7390/market.shopnow.app V/FA: Using measurement service
> 05-17 18:54:30.256 6007-7390/market.shopnow.app V/FA: Connection attempt already in progress
> 05-17 18:54:30.256 6007-7390/market.shopnow.app V/FA: Activity paused, time: 322629550
> 05-17 18:54:30.284 6007-6007/market.shopnow.app V/AddAdsWizard: 42141
> 05-17 18:54:30.284 6007-6007/market.shopnow.app V/test: 42141

yes it's enable.

**Comment by JaviChaques** [comment]
I have the same issue

**Comment by ankurgecr** [comment]
Same issue here.

![mediapicker_exception](https://user-images.githubusercontent.com/9653850/32839400-4cd48124-ca3a-11e7-8246-01afe13e3b43.png)

**Comment by alhazmy13** [comment]
Fixed with version `2.4.0`
