### ISSUE TITLE
hi , readme error

### ISSUE THREAD

**Issue by 13120241790** [alhazmy13/MediaPicker#26]
if (requestCode == VideoPicker.VIDEO_PICKER_REQUEST_CODE && resultCode == RESULT_OK) {
            List<String> mPaths = (List<String>) data.getSerializableExtra(ImagePicker.EXTRA_VIDEO_PATH);
            //Your Code
        }

need change ImagePicker.EXTRA_VIDEO_PATH  replace VideoPicker.EXTRA_VIDEO_PATH

**Comment by alhazmy13** [comment]
Hi @13120241790 
It should be fixed with commit  50384523ef188a11ad91c9c6d60c3a1f5d792a06

Thanks
