### ISSUE TITLE
Camera preview upsidedown

### ISSUE THREAD

**Issue by abalta** [alhazmy13/MediaPicker#32]
Captured image from camera looks upsidedown. I think you should check Exif rotation.

**Comment by alhazmy13** [comment]
Hi @abalta 

This issue should be fixed with below method: https://github.com/alhazmy13/MediaPicker/blob/master/libary/src/main/java/net/alhazmy13/mediapicker/Utility.java#L71

What's the android version that you are using? and what type of device? is it Samsung or emulator?

**Comment by abalta** [comment]
Android version is 7.1.2 with real device.

**Comment by abalta** [comment]
Right now, it is working thanks.
