### ISSUE TITLE
NullPointerException on cancelling VideoPicker

### ISSUE THREAD

**Issue by ATizik** [alhazmy13/MediaPicker#36]
If user chooses to upload video through gallery, but then cancels, an app throws NullPointerException.

new VideoPicker.Builder(activity)
                                    .mode(VideoPicker.Mode.CAMERA_AND_GALLERY)
                                    .directory(VideoPicker.Directory.DEFAULT)
                                     .build();

08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at net.alhazmy13.mediapicker.Video.VideoActivity.processOneVideo(VideoActivity.java:223)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at net.alhazmy13.mediapicker.Video.VideoActivity.processVideo(VideoActivity.java:203)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at net.alhazmy13.mediapicker.Video.VideoActivity.onActivityResult(VideoActivity.java:176)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6235)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:151)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at android.os.Looper.loop(Looper.java:135)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
08-18 13:49:00.641 25335-25335/com.example.atizik.testrdp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by alhazmy13** [comment]
Hi @ATizik 
Can you please provide more details, are you using a real device or with the emulator? And if it real with kind of devices?

**Comment by ATizik** [comment]
Real device, Lenovo PB1-770M, stock Android 5.1.1
