### ISSUE TITLE
image is not set

### ISSUE THREAD

**Issue by pandeyankur0007** [alhazmy13/MediaPicker#45]
I am using your lib in own project but i face issue image is not set sometime please help

**Comment by pandeyankur0007** [comment]
When i choose photo from gallery and click camera sometime is not set. Help please

**Comment by alhazmy13** [comment]
Hi @pandeyankur0007 
Can you give more details about your issue? What kind of device do you have?

**Comment by pandeyankur0007** [comment]
`@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == ImagePicker.IMAGE_PICKER_REQUEST_CODE && resultCode == RESULT_OK) {
            List<String> mPaths = (List<String>) data.getSerializableExtra(ImagePicker.EXTRA_IMAGE_PATH);
            filePath = mPaths.get(0);
            RoundedBitmapDrawable circularBitmapDrawable =
                    RoundedBitmapDrawableFactory.create(activity.getResources(), BitmapFactory.decodeFile(mPaths.get(0)));
            circularBitmapDrawable.setCircular(true);
            iv_user_profile.setImageDrawable(circularBitmapDrawable);
            iv_background.setImageBitmap(BitmapFactory.decodeFile(mPaths.get(0)));
        }
    }
`
**some time image is set not every time. Device moto G(2nd generation).**
