### ISSUE TITLE
set requestCode

### ISSUE THREAD

**Issue by amirhoseinpourali** [alhazmy13/MediaPicker#69]
Hi , Thanks for your good library.
I want set request code and handle this in Activity Result.
something like this:

`new ImagePicker.Builder(NewsActivity.this)`
          `       .mode(ImagePicker.Mode.GALLERY)`
          `       .compressLevel(ImagePicker.ComperesLevel.MEDIUM)`
          `       .directory(ImagePicker.Directory.DEFAULT)`
          `       .scale(300, 300)`
          `       .allowMultipleImages(true)`
          `       .enableDebuggingMode(true)`
          `       .setRequestCode(100)`
          `       .build();`

**Comment by arnaud33200** [comment]
I was looking for this kind of feature too! I might do a pull request if not exist yet ^^

**Comment by alhazmy13** [comment]
Fixed with [Version 2.4.4](https://github.com/alhazmy13/MediaPicker/releases/tag/2.4.4) 
Thanks
