### ISSUE TITLE
SDK 19+ External Storage (SD Card) Not working

### ISSUE THREAD

**Issue by mikemike396** [alhazmy13/MediaPicker#72]
So I have noticed my app not getting images via the SD card. I tired it on the latest demo app (2.4.1 beta) and it doesnt work either, please see the video. This is a pixel 2 running API 26. It also happens on many other devices. You can see the crash log below for my personal app related to a null URI. Any thoughts? It appears to be an issue with this line

    if ("primary".equalsIgnoreCase(type)) {
         return Environment.getExternalStorageDirectory() + "/" + split[1];
    }

![screen shot 2018-07-24 at 9 34 25 am](https://user-images.githubusercontent.com/14999806/43141801-d37005b4-8f24-11e8-8f9c-be9c5a59e79f.png)

![pickerexstoragenotworking](https://user-images.githubusercontent.com/14999806/43141490-fe601814-8f23-11e8-9738-de3d0ee7241a.gif)

![screen shot 2018-07-24 at 9 31 36 am](https://user-images.githubusercontent.com/14999806/43141634-67d3e424-8f24-11e8-9c1a-0c1c809c0045.png)

**Comment by alhazmy13** [comment]
Fixed with [Version 2.4.4](https://github.com/alhazmy13/MediaPicker/releases/tag/2.4.4) 
Thanks
