### ISSUE TITLE
Can't be able to Select Multipe Images

### ISSUE THREAD

**Issue by UttamPanchasara** [alhazmy13/MediaPicker#9]
when i try to select images from gallery i only can select 1 image and you have written in description that select Multiple image but i can't. im using Nexus 5 and with Marshmallow.

**Comment by alhazmy13** [comment]
i'll add it on next versions

**Comment by alhazmy13** [comment]
It's supported with version 2.2.2

Thank you 👍

**Comment by UttamPanchasara** [comment]
Thank you will check and update u on.
