### ISSUE TITLE
Failed to resolve: MediaPicker:libary:unspecified

### ISSUE THREAD

**Issue by rafalzawadzki** [alhazmy13/MediaPicker#93]
I am trying to use the rx extension, but unfortunately Gradle fails to resolve the dependency with an error `Failed to resolve: MediaPicker:libary:unspecified`

My dependencies:
```
implementation 'io.reactivex.rxjava2:rxjava:2.1.12'
implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
implementation 'io.reactivex.rxjava2:rxkotlin:2.2.0'
implementation 'net.alhazmy13.MediaPicker:rxjava:2.4.4'
```
also tried adding `implementation 'net.alhazmy13.MediaPicker:libary:2.4.4'` with no success.

**Comment by stevyhacker** [comment]
You have to add @aar at the end of dependencies for this to build successfully.
`    implementation 'net.alhazmy13.MediaPicker:libary:2.4.4@aar'
    implementation 'net.alhazmy13.MediaPicker:rxjava:2.4.4@aar'`

**Comment by rafalzawadzki** [comment]
worked, thanks!

**Comment by HBiSoft** [comment]
@rafalzawadzki `worked, thanks!` - Then close the issue
